---
title: "Exploratory Data Analysis"
author: "Shelby Tisdale"
format: html
---

```{r}
#| label: load-data-and-packages

# load packages
library(tidyverse)

# load data
expenditures <- read_csv("data/total_expenditures_2015_2022.csv")
```

```{r}
#| label: eda-bar
#| fig-height: 15
#| fig-width: 8
expenditures |>
  select(state, fiscal_year, funds_awarded, total_expenditures, fed_unliquidated, unobligated_balance) |>
  pivot_longer(cols = funds_awarded:unobligated_balance,
               names_to = "Type",
               values_to = "Amount") |>
  filter(fiscal_year == 2019 & state != "U.S. TOTAL") |>
  ggplot(aes(x = Amount, y = state)) +
  geom_col(aes(x = Amount, y = Type, fill = Type), show.legend = TRUE) +
  coord_cartesian(clip = "off") +
  facet_wrap(~state, ncol = 1, strip.position = "left") +
  theme_minimal() +
  theme(axis.text.y=element_blank(), 
      axis.ticks.y = element_blank(),
      strip.text.y.left = element_text(angle = 0),
      legend.position = "top")
```
```{r}
#| label: eda-line

expenditures |>
  select(state, fiscal_year, unobligated_balance, fed_unliquidated, funds_awarded) |>
  filter(state != "U.S. TOTAL" & state != "DIST.OF COLUMBIA") |>
  mutate(line_color = if_else(state == "MISSISSIPPI", "firebrick", "gray80")) |>
  ggplot(aes(x = fiscal_year, y = unobligated_balance)) +
  geom_line(aes(x = fiscal_year, y = unobligated_balance, group = state, color = line_color), show.legend = FALSE) +
  coord_cartesian(clip = "off") +
  scale_color_manual(values = c("firebrick", "gray80")) +
  #facet_wrap(~state, ncol = 1, strip.position = "left") +
  theme_minimal() +
  theme(#axis.text.y=element_blank(), 
      #axis.ticks.y = element_blank(),
      #strip.text.y.left = element_text(angle = 0),
      legend.position = "top")
```
```{r}
#| fig-width: 10
#| fig-height: 5

expenditures <- expenditures |>
  mutate(percent_cash_assistance = basic_assistance / total_expenditures)

expenditures |>
  filter(state != "U.S. TOTAL" & state != "DIST.OF COLUMBIA") |>
  ggplot(aes(x = log10(unobligated_balance), y = percent_cash_assistance*100), alpha = 0.5) +
  geom_point() +
  coord_cartesian(clip = "off") +
  #facet_wrap(~state, nrow = 5, ncol = 10) +
  theme_minimal()
```
```{r}
#| fig-width: 10
#| fig-height: 2
expenditures |>
  filter(state != "U.S. TOTAL" & state != "DIST. OF COLUMBIA") |>
  ggplot(aes(x = funds_awarded, y = total_expenditures)) +
  geom_point() +
  facet_wrap(~fiscal_year, nrow = 1) +
  theme_minimal()
```

```{r}
#| label: segmented-bar
#| fig-height: 12
#| fig-width: 10

# create a bar plot of total expenditures per year by state
expenditures_bar <- expenditures |>
  pivot_longer(cols = funds_awarded:unobligated_balance, names_to = "category", values_to = "amount") |>
  group_by(category, state) |>
  summarize(average_amount = mean(amount), .groups = "drop") |>
  mutate(category = case_when(
    category %in% c("basic_assistance_no_subsidies") ~ "Direct Cash Assistance",
    category %in% c("basic_assistance_subsidies", "other_assistance_foster",
                    "non_assistance_welfare_foster", "child_welfare") ~ "Child Welfare, Adoption, and Foster Care",
    category %in% c("other_assistance_juvenile_justice",
                    "non_assistance_juvenile_justice",
                    "children_youth_services") ~ "Juvenile Justice and Youth Services",
    category %in% c("work_ed", "work_supports", "financial_ed") ~ "Work, Education, and Training Activities",
    category %in% c("early_ed") ~ "Early Childcare and Education",
    category %in% c("support__services", "pregnancy_prevention", "fatherhood_programs", "home_visiting") ~ "Family Support and Formation Services",
    category %in% c("program_mgmt") ~ "Program Management",
    category %in% c("other", "other_assistance_emergency", "non_assistance_emergency", "eitc_refundable", "short_term_benefits", "non_eitc_refundable") ~ "Other",
    category == "unobligated_balance" ~ "Unobligated"
  )) |>
  filter(!is.na(category))

expenditures_bar |>
  mutate(category = fct_reorder(category, average_amount)) |>
  ggplot(aes(y = fct_rev(state))) +
  geom_col(aes(x = average_amount, fill = category), position = "fill") +
  #scale_fill_brewer(palette = "Dark2") +
  theme_minimal() +
  labs(y = NULL, x = "Average Amount of Funding Per Year")
```


