---
title: "tanf"
author: "Shelby Tisdale"
format: html
---

This repository contains all code and data for my senior honors thesis project at Duke University, "The Diminishing Cash Safety Net: Predicting Fulfillment of TANF Goals from Unobligated Funds with Bayesian Hierarchical Modeling. This is a developing project.

## Data

The document `sipp_data_cleaning.qmd` contains all code to create the final dataset `sipp_tanf.csv` included in the `\data` folder. Each variable in the dataset is at one of \_\_ levels to be included in the hierarchical model. The dataset contains 511497 observations of 36 variables. Each observation is an individual in a month.

### Data Dictionary

### `sipp_tanf.csv`

+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable                | Type        | Description                                                                                                                                                                                              |
+=========================+=============+==========================================================================================================================================================================================================+
| `household_id`          | ID; numeric | Household identifier. Can be used to match households in different survey years.                                                                                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household                                                                                                                                                                                     |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `pnum`                  | ID; numeric | Person number. Each individual in a household is given a distinct person number for that household.                                                                                                      |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `month`                 | numeric     | Reference month.                                                                                                                                                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `year`                  | numeric     | Survey panel year (reference year).                                                                                                                                                                      |
|                         |             |                                                                                                                                                                                                          |
|                         |             | Level: Household-year                                                                                                                                                                                    |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `age`                   | numeric     | Age as of last birthday                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-year                                                                                                                                                                                   |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `state`                 | character   | State of residence for the interview address.                                                                                                                                                            |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household                                                                                                                                                                                     |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `education`             | character   | Highest level of education received by December of reference year.                                                                                                                                       |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ethnicity`             | character   | Whether person is of Hispanic, Latino or Spanish origin.                                                                                                                                                 |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `race`                  | character   | Race (detailed categories).                                                                                                                                                                              |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `sex`                   | character   | Sex assigned at birth.                                                                                                                                                                                   |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `citizenship`           | numeric     | Whether person is a U.S. citizen.                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `total_children`        | numeric     | Children ever born or fathered.                                                                                                                                                                          |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household-month                                                                                                                                                                               |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `in_goal1`              | numeric     | Indicator for whether household fits criteria to be evaluated for TANF Goal 1: "Provide assistance to needy families so that children can be cared for in their own homes or in the homes of relatives." |
|                         |             |                                                                                                                                                                                                          |
|                         |             | `in_goal1` = 1 if at least one child lives in household during any year of the survey.                                                                                                                   |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household-month                                                                                                                                                                               |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `in_goal2`              | numeric     | Indicator for whether household fits criteria to be evaluated for TANF Goal 2: "End the dependence of needy parents on government benefits by promoting job preparation, work, and marriage."            |
|                         |             |                                                                                                                                                                                                          |
|                         |             | `in_goal2` = 1 if household is receiving any kind of government benefits in their earliest year of participation in the study (during reference time frame).                                             |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household                                                                                                                                                                                     |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `in_goal3`              | numeric     | Indicator for whether household fits criteria to be evaluated for TANF Goal 3: "Prevent and reduce the incidence of out-of-wedlock pregnancies"                                                          |
|                         |             |                                                                                                                                                                                                          |
|                         |             | `in_goal3` = 1 if person is a woman over the age of 14 and is unmarried in reference year.\                                                                                                              |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `in_goal4`              | numeric     | Indicator for whether household fits criteria to be evaluated for TANF Goal 4: "Encourage the formation and maintenance of two-parent families."                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | `in_goal4` = 1 if household includes at least one child and at least one parent.                                                                                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household                                                                                                                                                                                     |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `goal1`                 | numeric     | Indicates whether TANF Goal 1 is fulfilled for the given household and month.                                                                                                                            |
|                         |             |                                                                                                                                                                                                          |
|                         |             | `goal1` = 1 if all children in the household have at least one relative in the household.                                                                                                                |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household-month                                                                                                                                                                               |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `goal2`                 | numeric     | Indicates whether TANF Goal 2 is fulfilled for the given household.                                                                                                                                      |
|                         |             |                                                                                                                                                                                                          |
|                         |             | `goal2` = 1 if household members are no longer receiving government benefits by the end of the reference period.                                                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household                                                                                                                                                                                     |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `goal3`                 | numeric     | Indicates whether TANF Goal 3 is fulfilled for the given person.                                                                                                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | `goal3` = 1 if the number of children of an unmarried individual does not increase during the reference period.                                                                                          |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `goal4`                 | numeric     | Indicates whether TANF Goal 4 is fulfilled for the given household.                                                                                                                                      |
|                         |             |                                                                                                                                                                                                          |
|                         |             | If the household is a one-parent family, `goal4` = 1 if the family is a two-parent family at the end of the reference period.                                                                            |
|                         |             |                                                                                                                                                                                                          |
|                         |             | If the household is a two-parent family, `goal4` = 1 if the family is still a two-parent family at the end of the reference period.                                                                      |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Household                                                                                                                                                                                     |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `pct_unobligated`       | numeric     | Percent of available TANF funds unobligated. Calculated by dividing unobligated balance for fiscal year by the sum of awarded yearly funds and carryover from previous year.                             |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** State-year                                                                                                                                                                                    |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [TANF Financial Data](https://www.acf.hhs.gov/ofa/programs/tanf/data-reports){.uri}                                                                                             |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `pct_program_mgmt`      | numeric     | Percent of total expenditures allotted to program management expenses (administrative costs, assessment & service provision, systems)                                                                    |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** State-year                                                                                                                                                                                    |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [TANF Financial Data](https://www.acf.hhs.gov/ofa/programs/tanf/data-reports){.uri}                                                                                             |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `pct_basic_assistance`  | numeric     | Percent of total expenditures allotted to basic assistance (cash, payments, vouchers, and other forms of benefits designed to meet a family's ongoing basic needs).                                      |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** State-year                                                                                                                                                                                    |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from derived from [TANF Financial Data](https://www.acf.hhs.gov/ofa/programs/tanf/data-reports){.uri}                                                                                |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `received_job_training` | numeric     | Indicator for whether person received any kind of job training in reference month.                                                                                                                       |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [TANF Financial Data](https://www.acf.hhs.gov/ofa/programs/tanf/data-reports){.uri}                                                                                             |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `hh_married_month`      | numeric     | Indicates whether householder is married in reference month.                                                                                                                                             |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person                                                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** derived from [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                        |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_begin_month`      | numeric     | Beginning month of TANF receipt.                                                                                                                                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_initial_year`     | numeric     | Initial year of TANF benefit receipt.                                                                                                                                                                    |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_end_month`        | numeric     | End month of TANF benefit receipt.                                                                                                                                                                       |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_coverage_type`    | character   | Type of TANF benefit coverage.                                                                                                                                                                           |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_owner`            | numeric     | Person number for owner of TANF benefit this month.                                                                                                                                                      |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_continue_flag`    | character   | Continuation status of TANF benefit receipt in the last month of the reference period.                                                                                                                   |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_received_month`   | numeric     | Whether person received TANF benefits this month.                                                                                                                                                        |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_received_year`    | numeric     | Whether person received TANF benefits this year.                                                                                                                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-year                                                                                                                                                                                   |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `tanf_amt_received`     | numeric     | Value of the TANF benefits received this month.                                                                                                                                                          |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** Person-month                                                                                                                                                                                  |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Survey of Income and Program Participation Data](https://www.census.gov/programs-surveys/sipp/data/datasets.html){.uri}                                                                     |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `party`                 | character   | Political party affiliation of state's governor.                                                                                                                                                         |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Level:** State-year                                                                                                                                                                                    |
|                         |             |                                                                                                                                                                                                          |
|                         |             | **Source:** [Wikipedia List of States' Governors](https://en.wikipedia.org/wiki/Category:Lists_of_state_governors_of_the_United_States){.uri}                                                            |
+-------------------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
